{% set name = "metacooc" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Prefer PyPI sdist for reproducible builds:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f  # <- update if you switch to PyPI sdist

build:
  noarch: python
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas
    - scipy
    - matplotlib

test:
  imports:
    - metacooc
  commands:
    - metacooc --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bcoltman/metacooc
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Co-occurrence analysis of microorganisms in metagenomes.
  doc_url: https://metacooc.readthedocs.io
  dev_url: https://github.com/bcoltman/metacooc

extra:
  recipe-maintainers:
    - bcoltman
    - dspeth